# Generated by Django 3.2.7 on 2021-10-30 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_alter_result_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
